version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev-sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - D:/backup:/backup

volumes:
  mssql_data:
